import type { ReasoningCase } from "./types";

/**
 * The ds4-eval hard suite, assembled 2026-09-03: MMLU-Pro (Apache-2.0),
 * OlympiadBench (Apache-2.0), LiveBench reasoning (Apache-2.0) and locally
 * written reductions of NIST Juliet 1.3 weakness patterns (CC0). Meant for
 * large models; the core deck stays the 12B floor check.
 */
export const HARD_CASES: ReasoningCase[] = [
  {
    source: "MMLU-Pro",
    id: "2826",
    domain: "biology",
    title: "Biology challenge",
    question:
      "A gene C mutates to c with a frequency of 2 × 10^-6 per generation. There are no other forces acting on these alleles and mating is random. How many generations are needed to increase the frequency of gene c from 2 percent to 3 percent?",
    choices: [
      "2,500 generations",
      "6,200 generations",
      "15,000 generations",
      "8,764 generations",
      "10,000 generations",
      "20,000 generations",
      "3,000 generations",
      "1,000 generations",
      "7,500 generations",
      "5,128 generations",
    ],
    answer: "J",
    maxTokens: 4096,
  },
  {
    source: "MMLU-Pro",
    id: "86",
    domain: "business",
    title: "Business challenge",
    question:
      "The stock of the CCC Corporation is currently valued at $12 and is assumed to possess all the properties of geometric Brownian motion. It has an expected annual return of 15%, an annual volatility of 20%, and the annual risk-free is 10%. Using a binomial lattice, determine the price of a call option on CCC stock maturing in 10 monthes time with a strike price of $14 (Let the distance between nodes on your tree be 1 month in length).",
    choices: [
      "50.0",
      "60.0",
      "55.0",
      "44.0",
      "48.0",
      "53.0",
      "42.0",
      "46.0",
      "51.0",
      "45.0",
    ],
    answer: "F",
    maxTokens: 4096,
  },
  {
    source: "MMLU-Pro",
    id: "3546",
    domain: "chemistry",
    title: "Chemistry challenge",
    question:
      "Suppose that the normalized wavefunction for an electron in a carbon nanotube of length $L=10.0 \\mathrm{~nm}$ is: $\\psi=(2 / L)^{1 / 2} \\sin (\\pi x / L)$. Calculate the probability that the electron is between $x=4.95 \\mathrm{~nm}$ and $5.05 \\mathrm{~nm}$.",
    choices: [
      "0.020",
      "0.050",
      "0.030",
      "0.045",
      "0.010",
      "0.015",
      "0.035",
      "0.060",
      "0.025",
      "0.040",
    ],
    answer: "A",
    maxTokens: 4096,
  },
  {
    source: "MMLU-Pro",
    id: "10360",
    domain: "computer science",
    title: "Computer Science challenge",
    question:
      "Two expressions E and F are said to be unifiable if there are substitutions for the variables of E and F that make the expressions lexically identical. In the following three expressions, only w, x, y, and z are variables.\nI. f(w,w)\nII. f(x,1)\nIII. f(y,g(z))\nWhich pairs of these expressions is (are) pairs of unifiable expressions?",
    choices: [
      "(I, III) and (II, III) only",
      "(II, III) only",
      "(I, II) and (I, III) only",
      "(I, II) only",
      "Only single expressions are unifiable, not pairs",
      "None of the pairs are unifiable",
      "(I, II), (I, III), and (II, III)",
      "All three expressions are unifiable",
      "(I, II) and (II, III) only",
      "(I, III) only",
    ],
    answer: "C",
    maxTokens: 4096,
  },
  {
    source: "MMLU-Pro",
    id: "6844",
    domain: "economics",
    title: "Economics challenge",
    question:
      'The purpose of "augmenting" the Dickey-Fuller test regression is to',
    choices: [
      "Ensure that there is no heteroscedasticity in the test regression residuals.",
      "Improve the accuracy of the Dickey-Fuller test",
      "Ensure that the test regression residuals are negatively skewed",
      "Ensure that the test regression residuals are normally distributed",
      "Ensure that all of the non-stationarity is taken into account.",
      "Ensure that the test regression residuals have no outliers",
      "Ensure that the test regression residuals are positively skewed",
      "Ensure that there is no autocorrelation in the test regression residuals",
      "Ensure that the test regression residuals are balanced",
      "Increase the complexity of the Dickey-Fuller test",
    ],
    answer: "H",
    maxTokens: 4096,
  },
  {
    source: "MMLU-Pro",
    id: "11292",
    domain: "engineering",
    title: "Engineering challenge",
    question:
      "Calculate the entropy change for (a) H_2O (s, - 20°C, 1atm) \\rightarrow H_2O (s, 0°C, 1atm) (b) H_2O (s, - 20°C, 1atm) \\rightarrow H_2O (1, 20°C, 1atm) Assume C_p (H_2O, 1) = 18 cal deg^-1 mole^-1, C_p (H_2O, s) = 9 cal deg^-1 mole^-1 and\\DeltaH_fusion= 1440 cal deg^-1 mole^-1, andalso that the heat capacities are independent of temperature.",
    choices: [
      "0.68eu/mole for (a) and 7.22eu for (b)",
      "1.27eu/mole for (a) and 7.22eu for (b)",
      "0.68eu/mole for (a) and 5.27eu for (b)",
      "1.27eu/mole for (a) and 5.27eu for (b)",
    ],
    answer: "A",
    maxTokens: 4096,
  },
  {
    source: "MMLU-Pro",
    id: "6034",
    domain: "health",
    title: "Health challenge",
    question:
      "A 23-year-old woman with bone marrow failure is treated with a large dose of rabbit antithymocyte globulin. Ten days later, she develops fever, lymphadenopathy, arthralgias, and erythema on her hands and feet. Which of the following is the most likely cause of these symptoms?",
    choices: [
      "Activation of complement system",
      "Overproduction of monocytes",
      "Cytokine secretion by natural killer cells",
      "Hyperactive B-lymphocyte response",
      "Allergic reaction to rabbit proteins",
      "Immune complex deposition in tissues",
      "Polyclonal T-lymphocyte activation",
      "Eosinophil degranulation",
      "Increased production of interferon-gamma",
      "Acute graft-versus-host disease",
    ],
    answer: "F",
    maxTokens: 4096,
  },
  {
    source: "MMLU-Pro",
    id: "4699",
    domain: "history",
    title: "History challenge",
    question:
      'This question refers to the following information.\n"At least one of the [world\'s] societies would have to somehow enormously increase its productivity [in order to achieve global hegemony]. That quantum jump would have to be made before the various scientific, technological, agricultural, and industrial revolutions on which our post-quantum-leap world rests. It could only be accomplished by exploiting the ecosystems, mineral resources, and human assets of whole continents outside the lands of the society making the jump. Western Europe did just that by means of its brutality and guns and, more important, by geographical and ecological luck."\nCopyright © 2015 Cambridge University Press.\nAlfred Crosby, historian, Ecological Imperialism, 2004\nBased on your knowledge of world history, which of the following contributed LEAST to Western European global hegemony between 1450 and 1750 C.E.?',
    choices: [
      "The implementation of joint-stock companies",
      "The exploitation of labor in colonized regions",
      "The exploration of new sea routes to Asia and the Americas",
      "The establishment of trading posts along Asian and African coasts",
      "The exchange of food sources between the Americas and Europe",
      "The spread of Christianity to non-European regions",
      "The development and application of steam-powered technologies",
      "The discovery and colonization of the Americas",
      "The development of advanced naval technology",
      "Refinement of gunpowder technologies",
    ],
    answer: "G",
    maxTokens: 4096,
  },
  {
    source: "MMLU-Pro",
    id: "899",
    domain: "law",
    title: "Law challenge",
    question:
      "A man and a woman were passengers on a plane. They were seated next to one another in the first- class section of the plane. Midway through the flight, the woman excused herself and went to the restroom. While she was gone, the man rummaged through the woman's purse and stole $100 in cash. Unknown to the man, a flight attendant saw him steal the money. As is customary in such situations, the flight attendant radioed ahead, and police officers arrested the man when the plane landed. The man was subsequently charged with violating an applicable federal larceny statute. During the trial, the prosecuting attorney called the man's wife as a willing witness against her husband. She proposed to testify that the man confided to her that he did steal the woman's money during the flight. The man's attorney objected on the grounds of hearsay and privilege. The wife's proposed testimony is",
    choices: [
      "admissible, because it is privileged, though it is not hearsay.",
      "admissible, because it is neither hearsay nor privileged.",
      "admissible, because it is hearsay within a recognized exception and not privileged.",
      "inadmissible, both because it discloses a privileged communication and because it is hearsay not within any recognized exception.",
      "admissible, both because it discloses a privileged communication and because it is hearsay not within any recognized exception.",
      "inadmissible, because it is hearsay not within any recognized exception, and it discloses a privileged communication.",
      "inadmissible, because it discloses a privileged communication, though it is not hearsay.",
      "admissible, both because it does not disclose a privileged communication and because it is hearsay within a recognized exception.",
      "inadmissible, because it is hearsay within a recognized exception, though it is not privileged.",
      "inadmissible, because it is hearsay not within any recognized exception, though it is not privileged.",
    ],
    answer: "G",
    maxTokens: 4096,
  },
  {
    source: "MMLU-Pro",
    id: "7738",
    domain: "math",
    title: "Math challenge",
    question:
      "Suppose that $f(x)$ is a polynomial that has degree $6$ and $g(x)$ is a polynomial that has degree $3$. If $h(x)$ is also a polynomial such that $f(g(x)) + g(h(x)) + h(f(x))$ is a polynomial of degree $36$, then what is the degree of the polynomial $h$?",
    choices: ["3", "21", "6", "9", "30", "72", "12", "15", "24", "18"],
    answer: "C",
    maxTokens: 4096,
  },
  {
    source: "MMLU-Pro",
    id: "5078",
    domain: "other",
    title: "Other challenge",
    question:
      "Are strategies of Arms Control and Deterrence useful in cyber-security?",
    choices: [
      "No, arms control does not serve any purpose outside the realm of traditional military weapons.",
      "Arms control strategies can be implemented, but deterrence strategies are impossible due to the anonymous nature of cyber attacks.",
      "Yes, both strategies are effective in cyber-security as long as there is strong international cooperation and regulation.",
      "Effective deterrence requires international cooperation which is achievable in theory, but the verification required for traditional arms control strategies is impossible in cyber(ed) warfare.",
      "Only arms control is unproblematic, deterrence has failed because international cooperation cannot be reached and common rules or practices cannot be established.",
      "Both strategies can only work if there is a clear agreement on what constitutes a cyber weapon and what constitutes a cyber attack.",
      "Yes, successful policies of arms control and deterrence have translated well from other security realms, such as nuclear weapons control strategies.",
      "Deterrence is ineffective because it encourages an arms race in cyberspace, while arms control is difficult due to the ease of creating and distributing cyber weapons.",
      "Both arms control and deterrence strategies are ineffective due to the rapid and unpredictable development of cyber warfare technologies.",
      "No, both strategies are obsolete in the face of cyber warfare's unique challenges such as attribution and boundary issues.",
    ],
    answer: "D",
    maxTokens: 4096,
  },
  {
    source: "MMLU-Pro",
    id: "10775",
    domain: "philosophy",
    title: "Philosophy challenge",
    question:
      " Construct a complete truth table for the following pairs of propositions. Then, using the truth tables, determine whether the statements are logically equivalent or contradictory. If neither, determine whether they are consistent or inconsistent. Justify your answers.\n(~M ⊃ ~N) ∨ (O ≡ N) and (~M · N) · [(~O ∨ ~N) · (O ∨ N)]",
    choices: [
      "Both logically equivalent and consistent",
      "Both consistent and contradictory",
      "Both logically equivalent and contradictory",
      "Contradictory",
      "Neither logically equivalent nor contradictory, but inconsistent",
      "Logically equivalent",
      "Both inconsistent and contradictory",
      "Inconsistent",
      "Neither logically equivalent nor contradictory, but consistent",
      "Neither logically equivalent nor inconsistent, but contradictory",
    ],
    answer: "D",
    maxTokens: 4096,
  },
  {
    source: "MMLU-Pro",
    id: "9055",
    domain: "physics",
    title: "Physics challenge",
    question:
      "Two spaceships approach Earth with equal speeds, as measured by an observer on Earth, but from opposite directions. A meterstick on one spaceship is measured to be 60 cm long by an occupant of the other spaceship. What is the speed of each spaceship, as measured by the observer on Earth?",
    choices: [
      "0.4c",
      "0.1c",
      "1.0c",
      "0.9c",
      "0.2c",
      "0.5c",
      "0.6c",
      "0.3c",
      "0.8c",
      "0.7c",
    ],
    answer: "F",
    maxTokens: 4096,
  },
  {
    source: "MMLU-Pro",
    id: "1995",
    domain: "psychology",
    title: "Psychology challenge",
    question:
      "An examinee who makes a number of confabulatory responses on the Rorschach has overgeneralized from a part of the inkblot to the whole. Such responses suggest which of the following?",
    choices: [
      "an inability to perceive abstract concepts",
      "high level of stress or anxiety",
      "a low level of self-esteem",
      "high intelligence and creativity",
      "a lack of attention to detail",
      "a need for immediate gratification",
      "brain damage, intellectual disability, or emotional disturbance",
      "a high degree of defensiveness or denial",
      "a highly imaginative personality",
      "a high degree of introversion or social withdrawal",
    ],
    answer: "G",
    maxTokens: 4096,
  },
  {
    source: "MMLU-Pro",
    id: "7754",
    domain: "math",
    title: "Math challenge",
    question:
      "How many triangles are there whose sides are all integers and whose maximum side length equals 11?",
    choices: ["45", "36", "48", "33", "50", "55", "24", "42", "30", "60"],
    answer: "B",
    maxTokens: 4096,
  },
  {
    source: "MMLU-Pro",
    id: "3024",
    domain: "biology",
    title: "Biology challenge",
    question:
      'Two 30" plants are crossed, resulting in progeny of the following ratio: one 22", eight 24\\textquotedblright, twenty-eight 26", fifty-six 28", seventy 30", fifty-six 32", twenty-eight 34", eight 36", and one 38". Starting with A and going through the alphabet to represent different alleles, what are the most probable genotypes of the parents?',
    choices: [
      "AaBbCcDd×AABBCCDD",
      "AaBbCcEeFf×AaBbCcEeFf",
      "AaBbCc×AaBbCc",
      "AaBb×AaBb",
      "AaBbCcDd×AaBbCcDd",
      "AaBbCcDdEe×AaBbCcDdEe",
      "Aa×Aa",
      "AaBbDd×AaBbDd",
      "AaBbCc×AaBb",
      "AABB×AABB",
    ],
    answer: "E",
    maxTokens: 4096,
  },
  {
    source: "MMLU-Pro",
    id: "671",
    domain: "business",
    title: "Business challenge",
    question:
      "Frank Bryant is a salesman for the Fast Cool Refrigerator Co. He is compensated for all travel expenses, and is allowed a drawing account of $600 per month. He receives a monthly commission of 2% of his first $30,000 of sales, 2.5% of the next $10,000 of sales, and 3% of all sales in excess of $40,000. Find the amount due him for a month in which his travel expenses paid out of pocket are $332.75, his drawings are $600, and his sales total $41,180.",
    choices: [
      "$1,332.75",
      "$942.55",
      "$783.40",
      "$618.15",
      "$725.15",
      "$1,035.40",
      "$885.40",
      "$1,118.15",
      "$1,218.15",
      "$332.75",
    ],
    answer: "D",
    maxTokens: 4096,
  },
  {
    source: "MMLU-Pro",
    id: "3696",
    domain: "chemistry",
    title: "Chemistry challenge",
    question:
      "2 moles of a monoatomic ideal gas at 45°C are compressed adiabatically and reversibly from 75 liters to 20 liters. Calculate q, W, \\DeltaH and \\DeltaE for the process, excluding vi-brationalcontributions.",
    choices: [
      "q=0, ΔE=15.00kJ, ΔH=22.50kJ",
      "q=11.21kJ, ΔE=0, ΔH=18.68kJ",
      "q=0, ΔE=18.68kJ, ΔH=11.21kJ",
      "q=18.68kJ, ΔE=18.68kJ, ΔH=18.68kJ",
      "q=0, ΔE=11.21kJ, ΔH=18.68kJ",
      "q=11.21kJ, ΔE=18.68kJ, ΔH=0",
      "q=22.50kJ, ΔE=15.00kJ, ΔH=0",
      "q=0, ΔE=22.50kJ, ΔH=15.00kJ",
      "q=18.68kJ, ΔE=11.21kJ, ΔH=0",
      "q=18.68kJ, ΔE=0, ΔH=11.21kJ",
    ],
    answer: "E",
    maxTokens: 4096,
  },
  {
    source: "MMLU-Pro",
    id: "10567",
    domain: "computer science",
    title: "Computer Science challenge",
    question:
      "Let F: K \\times R \\to MF:K×R→M be a secure PRF. For m \\in Mm∈M define E(k,m) = \\big[ r \\gets R,\\ \\text{output } \\big(r,\\ F(k,r) \\oplus m\\big)\\ \\big]E(k,m)=[r←R, output (r, F(k,r)⊕m) ] Is EE symantically secure under CPA?",
    choices: [
      "It depends on the size of R",
      "Yes, but only if R is large enough so r never repeats (w.h.p)",
      "Yes, but only if M is small enough so m never repeats (w.h.p)",
      "No, unless F is a weak PRF",
      "No, unless F is a strong PRF",
      "Yes, but only if K is large enough so k never repeats (w.h.p)",
      "It depends on the size of K",
      "No, there is always a CPA attack on this system",
      "It depends on what F is used",
      "Yes, whenever F is a secure PRF",
    ],
    answer: "B",
    maxTokens: 4096,
  },
  {
    source: "MMLU-Pro",
    id: "6955",
    domain: "economics",
    title: "Economics challenge",
    question:
      "Which of the following is included in U.S. GDP? I.   The market value of movies made in Africa by U.S. citizens II.   The market value of olive oil made in Italy and sold in the United States. III.   The market value of blue jeans made in the United States and sold in Japan IV.   The market value of wine made in the United States by Canadian citizens",
    choices: [
      "II and IV only",
      "I, II and IV only",
      "I only",
      "IV only",
      "I, II and III only",
      "I and IV only",
      "III and IV only",
      "I and III only",
      "II and III only",
      "II III and IV only",
    ],
    answer: "G",
    maxTokens: 4096,
  },
  {
    source: "MMLU-Pro",
    id: "11346",
    domain: "engineering",
    title: "Engineering challenge",
    question:
      "Calculate the loss of head in a pipe (1/4) in. in diameter and 16 ft. long, when water flows at half the critical velocity. The critical velocity occurs when Reynolds number is 2500. Take viscosity \\mu = 1.01 centipoise = 0.679 × 10^-3 lbm/ft-sec.",
    choices: [
      "3.12 in",
      "7.5 in",
      "0.8 in",
      "6.3 in",
      "2.5 in",
      "5.0 in",
      "1.75 in",
      "4.2 in",
      "4.8 in",
      "2.0 in",
    ],
    answer: "A",
    maxTokens: 4096,
  },
  {
    source: "MMLU-Pro",
    id: "6500",
    domain: "health",
    title: "Health challenge",
    question:
      "A 33-year-old man undergoes a radical thyroidectomy for thyroid cancer. During the operation, moderate hemorrhaging requires ligation of several vessels in the left side of the neck. Postoperatively, serum studies show a calcium concentration of 7.5 mg/dL, albumin concentration of 4 g/dL, and parathyroid hormone concentration of 200 pg/mL. Damage to which of the following vessels caused the findings in this patient?",
    choices: [
      "Branch of the costocervical trunk",
      "Branch of the external carotid artery",
      "Branch of the thyrocervical trunk",
      "Tributary of the internal jugular vein",
    ],
    answer: "C",
    maxTokens: 4096,
  },
  {
    source: "MMLU-Pro",
    id: "4674",
    domain: "history",
    title: "History challenge",
    question:
      "Recent discoveries of Homo naledi fossils in the Dinaledi Chamber of the Rising Star cave system in South Africa suggest a mixture of post-cranial morphologies or mosaic of hominid traits. One of the reasons this new species is controversial is that:",
    choices: [
      "the Homo naledi fossils were found in the same layer as modern human fossils, suggesting they lived at the same time.",
      "the Homo naledi fossils have traits that do not fit into the current understanding of hominid evolution.",
      "paleoanthropologists did not make the discovery and it was found in an inaccessible cave in South Africa.",
      "the fossils were found in a region previously thought to be inhabited by a different species of Homo.",
      "the Homo naledi fossils show traits of both Homo and Australopithecus, suggesting a potential hybrid species.",
      "the methods used to extract the fossils from the cave were controversial and potentially damaging to the specimens.",
      "there is, as yet, no firm date that can be applied to the specimens.",
      "the Homo naledi fossils have been shown to pre-date the earliest known hominid fossils by millions of years.",
      "there are already two well-known species of Homo and it is unlikely there were more than two species at one time.",
      "the researchers who discovered the fossils have been accused of falsifying their findings.",
    ],
    answer: "G",
    maxTokens: 4096,
  },
  {
    source: "MMLU-Pro",
    id: "1467",
    domain: "law",
    title: "Law challenge",
    question:
      'A motorcycle collector and his friend had known each other for years. The collector sent a letter to the friend that said, "I am willing to sell you my oldest motorcycle for $4,000." The friend sent the collector an email saying, "I accept your offer." The collector owned three motorcycles: a 1985 model, a 1987 model, and a 1992 model. The friend did not know about the 1985 model, which was the one the collector intended to sell. The collector was unaware that the friend intended to buy the 1987 model. When the collector tendered the 1985 model, the friend refused to accept it. Is the friend likely to prevail in a breach of contract suit against the collector?',
    choices: [
      "No, because it was the friend's responsibility to know the details about the collector's motorcycles before agreeing to purchase.",
      'No, because by not inquiring further about the meaning of the phrase "oldest motorcycle," the friend assumed the risk of being mistaken.',
      'No, the friend won\'t prevail as he misunderstood the term "oldest motorcycle".',
      "Yes, so long as a reasonable person in the friend's position would have considered the letter as referring to the 1987 model.",
      'No, because neither the friend nor the collector had reason to know of the other\'s interpretation of the words "oldest motorcycle."',
      "Yes, the friend will prevail as the collector falsely advertised the motorcycle model.",
      "No, because the friend should have asked for clarification about which model was being sold before agreeing to the purchase.",
      'Yes, because the friend could have reasonably assumed that the "oldest motorcycle" referred to the 1987 model, given his knowledge.',
      "Yes, because the friend had no reason to know of the collector's meaning and the collector could have avoided the confusion by more careful drafting.",
      "Yes, because the collector should have clarified which model he was referring to in the letter.",
    ],
    answer: "E",
    maxTokens: 4096,
  },
  {
    source: "MMLU-Pro",
    id: "8771",
    domain: "math",
    title: "Math challenge",
    question:
      "7.4-11. Some dentists were interested in studying the fusion of embryonic rat palates by a standard transplantation technique. When no treatment is used, the probability of fusion equals approximately 0.89 . The dentists would like to estimate $p$, the probability of fusion, when vitamin A is lacking.\n(a) How large a sample $n$ of rat embryos is needed for $y / n \\pm 0.10$ to be a $95 \\%$ confidence interval for $p$ ?",
    choices: ["70", "50", "45", "40", "30", "55", "$38$", "65", "60", "25"],
    answer: "G",
    maxTokens: 4096,
  },
  {
    source: "MMLU-Pro",
    id: "5848",
    domain: "other",
    title: "Other challenge",
    question:
      "Lake Trust a simple trust reported the following items of income and expense during the year: Dividend income $2500 Taxable interest income 2000 Capital gains (allocable to corpus) 5000 Accounting fees (allocable to income) (500) Trustee fees (allocable to income) (750) What is Lake's distributable net income?",
    choices: [
      "$5,000",
      "$6,000",
      "$9,500",
      "$2,000",
      "$4,500",
      "$10,000",
      "$8,250",
      "$7,500",
      "$1,750",
      "3250",
    ],
    answer: "J",
    maxTokens: 4096,
  },
  {
    source: "MMLU-Pro",
    id: "11120",
    domain: "philosophy",
    title: "Philosophy challenge",
    question:
      " Use indirect truth tables to determine whether each set of propositions is consistent. If the set is consistent, choose an option with a consistent valuation. (There may be other consistent valuations.)\nD ≡ E\nF ∨ D\n~E · ~F",
    choices: [
      "Consistent. Consistent valuation when D and E are true and F is true",
      "Inconsistent",
      "Consistent. Consistent valuation when D is true, E and F are false",
      "Consistent. Consistent valuation when E is true, D and F are false",
      "Consistent. Consistent valuation when D and E are true and F is false",
      "Consistent. Consistent valuation when D, E are false and F is true",
      "Consistent. Consistent valuation when D and F are true and E is false",
      "Consistent. Consistent valuation when D, E, and F are true",
      "Consistent. Consistent valuation when F is true, D and E are false",
      "Consistent. Consistent valuation when D, E and F are false",
    ],
    answer: "B",
    maxTokens: 4096,
  },
  {
    source: "MMLU-Pro",
    id: "9487",
    domain: "physics",
    title: "Physics challenge",
    question:
      "A gas sample is known to be a mixture of ethane and butane. A bulb having a $230.0 \\mathrm{~cm}^3$ capacity is filled with the gas to a pressure of $97.5 \\times 10^3 \\mathrm{~Pa}$ at $23.1^{\\circ} \\mathrm{C}$. If the mass of the gas in the bulb is $0.3554 \\mathrm{~g}$, what is the mole percent of butane in the mixture?\n",
    choices: [
      "70 %",
      "27 %",
      "50 %",
      "10 %",
      "60 %",
      "15 %",
      "25 %",
      "32 %",
      "45 %",
      "38 %",
    ],
    answer: "H",
    maxTokens: 4096,
  },
  {
    source: "MMLU-Pro",
    id: "2398",
    domain: "psychology",
    title: "Psychology challenge",
    question:
      'Susan is a first-grade student who is referred to the school psychologist because she will not remain seated at her desk. Her teacher reports that Susan is "always getting up and walking around the room." What observation data is LEAST relevant to the referral concern?',
    choices: [
      "Susan's academic performance",
      "The teacher's teaching style",
      "Number of students in the class",
      "The school's disciplinary policies",
      "Classroom environment",
      "Peer comparison",
      "Frequency",
      "Intensity",
      "Susan's diet",
      "Duration",
    ],
    answer: "H",
    maxTokens: 4096,
  },
  {
    source: "MMLU-Pro",
    id: "8863",
    domain: "math",
    title: "Math challenge",
    question:
      "An investor deposits $1000 in an account paying interest at a rate of 8% compounded monthly, and also makes additional deposits of \\$25 per month. Find the balance in the account after 3 years.",
    choices: [
      "$3200.67",
      "$2050.89",
      "$2100.45",
      "$1950.32",
      "$3000.59",
      "$2500.00",
      "2283.63 $",
      "$2750.48",
      "$2600.25",
      "$1800.75",
    ],
    answer: "G",
    maxTokens: 4096,
  },
  {
    source: "OlympiadBench",
    id: "1606",
    domain: "Combinatorics",
    title: "Olympiad problem 1606",
    question:
      "Xenia and Sergey play the following game. Xenia thinks of a positive integer $N$ not exceeding 5000. Then she fixes 20 distinct positive integers $a_{1}, a_{2}, \\ldots, a_{20}$ such that, for each $k=1,2, \\ldots, 20$, the numbers $N$ and $a_{k}$ are congruent modulo $k$. By a move, Sergey tells Xenia a set $S$ of positive integers not exceeding 20 , and she tells him back the set $\\left\\{a_{k}: k \\in S\\right\\}$ without spelling out which number corresponds to which index. How many moves does Sergey need to determine for sure the number Xenia thought of?",
    answer: "2",
    maxTokens: 16000,
  },
  {
    source: "OlympiadBench",
    id: "1613",
    domain: "Algebra",
    title: "Olympiad problem 1613",
    question:
      "Determine all positive integers $n$ satisfying the following condition: for every monic polynomial $P$ of degree at most $n$ with integer coefficients, there exists a positive integer $k \\leq n$, and $k+1$ distinct integers $x_{1}, x_{2}, \\ldots, x_{k+1}$ such that\n\n\n\n$$\n\nP\\left(x_{1}\\right)+P\\left(x_{2}\\right)+\\cdots+P\\left(x_{k}\\right)=P\\left(x_{k+1}\\right) .\n\n$$\n\n\nNote. A polynomial is monic if the coefficient of the highest power is one.",
    answer: "2",
    maxTokens: 16000,
  },
  {
    source: "OlympiadBench",
    id: "1614",
    domain: "Combinatorics",
    title: "Olympiad problem 1614",
    question:
      "Let $n$ be an integer greater than 1 and let $X$ be an $n$-element set. A non-empty collection of subsets $A_{1}, \\ldots, A_{k}$ of $X$ is tight if the union $A_{1} \\cup \\cdots \\cup A_{k}$ is a proper subset of $X$ and no element of $X$ lies in exactly one of the $A_{i}$ s. Find the largest cardinality of a collection of proper non-empty subsets of $X$, no non-empty subcollection of which is tight.\n\n\n\nNote. A subset $A$ of $X$ is proper if $A \\neq X$. The sets in a collection are assumed to be distinct. The whole collection is assumed to be a subcollection.",
    answer: "2n-2",
    aliases: ["2(n-1)"],
    kind: "text",
    maxTokens: 16000,
  },
  {
    source: "OlympiadBench",
    id: "1618",
    domain: "Number Theory",
    title: "Olympiad problem 1618",
    question:
      "Determine all prime numbers $p$ and all positive integers $x$ and $y$ satisfying $x^{3}+y^{3}=$ $p(x y+p)$. Report each solution once as $(x,y,p)$ with $x \\leq y$.",
    answer: "(1,8,19),(2,7,13),(4,5,7)",
    aliases: ["(4,5,7),(2,7,13),(1,8,19)"],
    kind: "sequence",
    maxTokens: 16000,
  },
  {
    source: "OlympiadBench",
    id: "1697",
    domain: "Combinatorics",
    title: "Olympiad problem 1697",
    question:
      "On a square table of 2011 by 2011 cells we place a finite number of napkins that each cover a square of 52 by 52 cells. In each cell we write the number of napkins covering it, and we record the maximal number $k$ of cells that all contain the same nonzero number. Considering all possible napkin configurations, what is the largest value of $k$ ?",
    answer: "3986729",
    maxTokens: 16000,
  },
  {
    source: "OlympiadBench",
    id: "1709",
    domain: "Number Theory",
    title: "Olympiad problem 1709",
    question:
      "For each positive integer $k$, let $t(k)$ be the largest odd divisor of $k$. Determine all positive integers $a$ for which there exists a positive integer $n$ such that all the differences\n\n$$\nt(n+a)-t(n), \\quad t(n+a+1)-t(n+1), \\quad \\ldots, \\quad t(n+2 a-1)-t(n+a-1)\n$$\n\nare divisible by 4 .",
    answer: "1,3,5",
    kind: "sequence",
    maxTokens: 16000,
  },
  {
    source: "OlympiadBench",
    id: "1716",
    domain: "Algebra",
    title: "Olympiad problem 1716",
    question:
      "Let $x_{1}, \\ldots, x_{100}$ be nonnegative real numbers such that $x_{i}+x_{i+1}+x_{i+2} \\leq 1$ for all $i=1, \\ldots, 100$ (we put $x_{101}=x_{1}, x_{102}=x_{2}$ ). Find the maximal possible value of the sum\n\n$$\nS=\\sum_{i=1}^{100} x_{i} x_{i+2}\n$$",
    answer: "25/2",
    aliases: ["12.5"],
    kind: "rational",
    maxTokens: 16000,
  },
  {
    source: "OlympiadBench",
    id: "1736",
    domain: "Number Theory",
    title: "Olympiad problem 1736",
    question:
      "Find the least positive integer $n$ for which there exists a set $\\left\\{s_{1}, s_{2}, \\ldots, s_{n}\\right\\}$ consisting of $n$ distinct positive integers such that\n\n$$\n\\left(1-\\frac{1}{s_{1}}\\right)\\left(1-\\frac{1}{s_{2}}\\right) \\ldots\\left(1-\\frac{1}{s_{n}}\\right)=\\frac{51}{2010}\n$$",
    answer: "39",
    maxTokens: 16000,
  },
  {
    source: "OlympiadBench",
    id: "1750",
    domain: "Combinatorics",
    title: "Olympiad problem 1750",
    question:
      "A diagonal of a regular 2006-gon is called odd if its endpoints divide the boundary into two parts, each composed of an odd number of sides. Sides are also regarded as odd diagonals.\n\nSuppose the 2006-gon has been dissected into triangles by 2003 nonintersecting diagonals. Find the maximum possible number of isosceles triangles with two odd sides.",
    answer: "1003",
    maxTokens: 16000,
  },
  {
    source: "OlympiadBench",
    id: "1766",
    domain: "Number Theory",
    title: "Olympiad problem 1766",
    question:
      "Determine all pairs $(x, y)$ of integers satisfying the equation\n\n$$\n1+2^{x}+2^{2 x+1}=y^{2}\n$$",
    answer: "(0,2),(0,-2),(4,23),(4,-23)",
    kind: "sequence",
    maxTokens: 16000,
  },
  {
    source: "LiveBench",
    id: "c833574b0ff6e8609bee19b36fabc48501cdcd9a64b99cd0422f54ada1acc53d",
    domain: "zebra_puzzle",
    title: "Zebra logic puzzle",
    question:
      "There are 4 people standing in a line. From left to right, they are numbered 1 to 4.\nEach person has a set of attributes: Beverage, Job, Movie-Genre, Transport.\nThe attributes have the following possible values:\nBeverage: lemonade, fanta, iced-tea, hot-chocolate\nJob: social-worker, software-developer, coach, accountant\nMovie-Genre: martial-arts, horror, documentary, satire\nTransport: skateboard, train, ship, helicopter\nEach person has a unique value for each attribute.\nYou know the following about the people:\nThe person who watches documentary is somewhere between the person who watches martial-arts and the person who is a accountant\nThe person who travels by skateboard is not anywhere to the left of the person who travels by train\nThe person who watches martial-arts and the person who drinks iced-tea have the same parity positions\nThe person who watches satire is not anywhere to the right of the person who watches horror\nThe person who is a accountant and the person who drinks hot-chocolate have the same parity positions\nThe person who travels by train and the person who drinks hot-chocolate have different parity positions\nEither the person who is a coach is the same as the person who travels by helicopter or the person who is a coach is the same as the person who watches documentary, but not both\nThe person who watches satire and the person who is a accountant have different parity positions\nThe person who watches satire is not anywhere to the right of the person who watches documentary\nThe person who travels by skateboard is the same as the person who watches horror or the person who drinks fanta is the same as the person who travels by skateboard or both\nThe person who drinks fanta is somewhere between the person who watches satire and the person who watches martial-arts\nThe person who is a social-worker and the person who travels by helicopter have the same parity positions\nThe person who is a accountant is not anywhere to the left of the person who travels by ship\nThe person who drinks iced-tea is not anywhere to the right of the person who drinks fanta\nIn the above, 'parity position' means the evenness or oddness of the person's position in the line.\nGiven this information, answer the following questions:\nWhat is the movie genre of the person who is a software-developer?\nWhat movie genre does the person who drinks hot-chocolate watch?\nWhat movie genre does the person in position 2 watch?\nAt what position is the person who watches horror?",
    answer: "satire, martial-arts, horror, 2",
    kind: "sequence",
    maxTokens: 8192,
  },
  {
    source: "LiveBench",
    id: "b7b7e331df4614775210ef5e524ed7f20c5fec6655fb0dd179c94e4d71170862",
    domain: "zebra_puzzle",
    title: "Zebra logic puzzle",
    question:
      "There are 3 people standing in a line. From left to right, they are numbered 1 to 3.\nEach person has a set of attributes: Beverage, Food, Movie-Genre, Nationality.\nThe attributes have the following possible values:\nBeverage: mirinda, cola, water\nFood: cauliflower, radish, zucchini\nMovie-Genre: family, spy, crime\nNationality: brazilian, german, canadian\nEach person has a unique value for each attribute.\nYou know the following about the people:\nThe person who is brazilian is somewhere between the person who is german and the person who drinks cola\nThe person who eats cauliflower is not anywhere to the right of the person who drinks cola\nThe person who drinks mirinda is somewhere between the person who drinks cola and the person who is german\nThe person who watches family and the person who eats radish have the same parity positions\nThe person who watches spy is not anywhere to the right of the person who watches family\nEither the person who is canadian is the same as the person who watches spy or the person who eats cauliflower is the same as the person who is canadian, but not both\nThe person who eats cauliflower is not anywhere to the right of the person who eats radish\nIn the above, 'parity position' means the evenness or oddness of the person's position in the line.\nGiven this information, answer the following questions:\nWhat movie genre does the person in position 1 watch?\nAt what position is the person who watches crime?\nAt what position is the person who eats zucchini?\nWhat movie genre does the person in position 3 watch?",
    answer: "crime, 1, 2, family",
    kind: "sequence",
    maxTokens: 8192,
  },
  {
    source: "LiveBench",
    id: "0daa7ca38beec4441b9d5c04d0b98912322926f0a3ac28a5097889d4ed83506f",
    domain: "web_of_lies_v2",
    title: "Web of lies",
    question:
      "In this question, assume each person either always tells the truth or always lies. Tala is at the movie theater. The person at the restaurant says the person at the aquarium lies. Ayaan is at the aquarium. Ryan is at the botanical garden. The person at the park says the person at the art gallery lies. The person at the museum tells the truth. Zara is at the museum. Jake is at the art gallery. The person at the art gallery says the person at the theater lies. Beatriz is at the park. The person at the movie theater says the person at the train station lies. Nadia is at the campground. The person at the campground says the person at the art gallery tells the truth. The person at the theater lies. The person at the amusement park says the person at the aquarium tells the truth. Grace is at the restaurant. The person at the aquarium thinks their friend is lying. Nia is at the theater. Kehinde is at the train station. The person at the theater thinks their friend is lying. The person at the botanical garden says the person at the train station tells the truth. The person at the aquarium says the person at the campground tells the truth. The person at the aquarium saw a firetruck. The person at the train station says the person at the amusement park lies. Mateo is at the amusement park. Does the person at the train station tell the truth? Does the person at the amusement park tell the truth? Does the person at the aquarium tell the truth?",
    answer: "no, yes, yes",
    kind: "sequence",
    maxTokens: 8192,
  },
  {
    source: "LiveBench",
    id: "9ee37b9a04ab050936c86b2c5bb7abbaa0bc0e737d59a7bff9ba11e9b4069c1d",
    domain: "web_of_lies_v2",
    title: "Web of lies",
    question:
      "In this question, assume each person either always tells the truth or always lies. Liam is at the movie theater. The person at the beach says the person at the restaurant tells the truth. Kehinde is at the aquarium. The person at the amusement park saw a firetruck. The person at the aquarium tells the truth. Luna is at the library. Jaxon is at the amusement park. The person at the amusement park says the person at the beach tells the truth. Anika is at the restaurant. The person at the barbershop tells the truth. The person at the observatory says the person at the planetarium lies. Hiroshi is at the beach. Isabella is at the planetarium. Nia is at the barbershop. The person at the movie theater says the person at the observatory lies. The person at the restaurant tells the truth. Max is at the observatory. The person at the library says the person at the amusement park tells the truth. The person at the planetarium says the person at the library tells the truth. Does the person at the movie theater tell the truth? Does the person at the observatory tell the truth? Does the person at the planetarium tell the truth?",
    answer: "yes, no, yes",
    kind: "sequence",
    maxTokens: 8192,
  },
  {
    source: "LiveBench",
    id: "d7071c9ff5d9779e7ab955366d0ae8db40f785aadfe7ff0b5a7ede98c05c44ea",
    domain: "web_of_lies_v2",
    title: "Web of lies",
    question:
      "In this question, assume each person either always tells the truth or always lies. Liam is at the restaurant. The person at the observatory says the person at the botanical garden lies. Elowen is at the vineyard. The person at the library says the person at the botanical garden tells the truth. The person at the train station tells the truth. The person at the botanical garden saw a firetruck. The person at the botanical garden says the person at the train station lies. Jake is at the aquarium. Soren is at the farm. Theo is at the gym. The person at the train station saw a firetruck. Devika is at the train station. Kehinde is at the library. The person at the restaurant lies. The person at the farm says the person at the train station lies. The person at the gym says the person at the train station lies. Hiroshi is at the botanical garden. The person at the vineyard lies. The person at the aquarium says the person at the library tells the truth. Quan is at the observatory. Does the person at the library tell the truth? Does the person at the botanical garden tell the truth? Does the person at the train station tell the truth?",
    answer: "no, no, yes",
    kind: "sequence",
    maxTokens: 8192,
  },
  {
    source: "NIST Juliet",
    id: "juliet-cwe190-int-multiply-01",
    domain: "CWE-190",
    title: "Integer multiplication overflow",
    question:
      "The following C function is intended to allocate space for count integers. Identify the line containing the primary weakness.\n\n 1  int *make_array(size_t count) {\n 2      int *result = NULL;\n 3      if (count == 0)\n 4          return NULL;\n 5      size_t bytes;\n 6      if (count > SIZE_MAX / sizeof(int))\n 7          return NULL;\n 8      bytes = count * sizeof(int);\n 9      result = malloc(bytes);\n10      if (result == NULL)\n11          return NULL;\n12      memset(result, 0, count * count * sizeof(int));\n13      return result;\n14  }",
    answer: "12",
    maxTokens: 4096,
  },
  {
    source: "NIST Juliet",
    id: "juliet-cwe121-array-index-01",
    domain: "CWE-121",
    title: "Stack array index validation",
    question:
      "The following C function should update one element of a fixed-size stack array. Identify the smallest exact set of line numbers containing the primary weakness.\n\n 1  int update_value(int index, int value) {\n 2      int data[10] = {0};\n 3      if (index < 10)\n 4          data[index] = value;\n 5      return data[0];\n 6  }",
    answer: "3-4",
    maxTokens: 4096,
  },
  {
    source: "NIST Juliet",
    id: "juliet-cwe401-realloc-01",
    domain: "CWE-401",
    title: "Lost allocation after realloc",
    question:
      "The following C function grows an allocated buffer. Identify the line containing the primary weakness.\n\n 1  char *grow(char *buf, size_t size) {\n 2      if (size > SIZE_MAX / 2)\n 3          return NULL;\n 4      size *= 2;\n 5      buf = realloc(buf, size);\n 6      if (buf == NULL)\n 7          return NULL;\n 8      return buf;\n 9  }",
    answer: "5",
    maxTokens: 4096,
  },
  {
    source: "NIST Juliet",
    id: "juliet-cwe476-null-after-deref-01",
    domain: "CWE-476",
    title: "Null check after dereference",
    question:
      "The following C function reads the first byte of a caller-supplied buffer. Identify the line containing the primary weakness.\n\n 1  int first_byte(const unsigned char *p) {\n 2      int value = p[0];\n 3      if (p == NULL)\n 4          return -1;\n 5      return value;\n 6  }",
    answer: "2",
    maxTokens: 4096,
  },
  {
    source: "NIST Juliet",
    id: "juliet-cwe369-int-divide-01",
    domain: "CWE-369",
    title: "Unchecked integer division",
    question:
      "The following C function computes a ratio from caller-supplied integers. Identify the line containing the primary weakness.\n\n 1  int ratio(int total, int parts) {\n 2      if (total < 0)\n 3          return -1;\n 4      return total / parts;\n 5  }",
    answer: "4",
    maxTokens: 4096,
  },
];
